<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
          "DTD/xhtml1-strict.dtd">
<html>
  

  <head>
    
    <title>django.core.exceptions</title>
    <meta name="generator" content="pydoctor 22.2.1"> 
        
    </meta>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=0.75" />
    <link rel="stylesheet" type="text/css" href="bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="apidocs.css" />
    <link rel="stylesheet" type="text/css" href="extra.css" />
</head>

  <body>

    <div id="banner">    
    <div>
        <a href="/">Home</a>
        &gt; django-4.0.2 <!-- This is a placeholder -->
        
        <!-- (<a href=""&gt;show all versions</a&gt;) -->
    </div>
</div>

    <nav class="navbar navbar-default">
  
  <div class="container">

    <div class="navbar-header">
      
      <div class="navlinks">
          <span class="navbar-brand">
            django <a href="index.html">API Documentation</a>
          </span>

          <a href="moduleIndex.html">
            Modules
          </a>

          <a href="classIndex.html">
            Classes
          </a>

          <a href="nameIndex.html">
            Names
          </a>
      </div>

    </div>
  </div>
</nav>

    

    <div class="container">

      <div class="page-header">
        <h1 class="module"><code><code><a href="index.html" class="internal-link">django</a></code><wbr></wbr>.<code><a href="django.core.html" class="internal-link" title="django.core">core</a></code><wbr></wbr>.<code><a href="django.core.exceptions.html" class="internal-link" title="django.core.exceptions">exceptions</a></code></code></h1>
        <div id="showPrivate">
          <button class="btn btn-link" onclick="togglePrivate()">Toggle Private API</button>
        </div>
      </div>

      <div class="categoryHeader">
        module documentation
      </div>

      <div class="extrasDocstring">
        <a href="https://github.com/pydocbrowser/pydocbrowser.github.io/tree/main/build/sources/django-4.0.2//django/core/exceptions.py" class="sourceLink">(source)</a>
        <p></p>
      </div>

      <div class="moduleDocstring">
        <div>Global Django exception and warning classes.</div>
      </div>

      <div id="splitTables">
        <table class="children sortable" id="id2270">
  
  
  <tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.AppRegistryNotReady.html" class="internal-link" title="django.core.exceptions.AppRegistryNotReady">​App​Registry​Not​Ready</a></code></td>
    <td>The django.apps registry is not populated yet</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.BadRequest.html" class="internal-link" title="django.core.exceptions.BadRequest">​Bad​Request</a></code></td>
    <td>The request is malformed and cannot be processed.</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.DisallowedHost.html" class="internal-link" title="django.core.exceptions.DisallowedHost">​Disallowed​Host</a></code></td>
    <td>HTTP_HOST header contains invalid value</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.DisallowedRedirect.html" class="internal-link" title="django.core.exceptions.DisallowedRedirect">​Disallowed​Redirect</a></code></td>
    <td>Redirect to scheme not in allowed list</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.EmptyResultSet.html" class="internal-link" title="django.core.exceptions.EmptyResultSet">​Empty​Result​Set</a></code></td>
    <td>A database query predicate is impossible.</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.FieldDoesNotExist.html" class="internal-link" title="django.core.exceptions.FieldDoesNotExist">​Field​Does​Not​Exist</a></code></td>
    <td>The requested model field does not exist</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.FieldError.html" class="internal-link" title="django.core.exceptions.FieldError">​Field​Error</a></code></td>
    <td>Some kind of problem with a model field.</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.ImproperlyConfigured.html" class="internal-link" title="django.core.exceptions.ImproperlyConfigured">​Improperly​Configured</a></code></td>
    <td>Django is somehow improperly configured</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.MiddlewareNotUsed.html" class="internal-link" title="django.core.exceptions.MiddlewareNotUsed">​Middleware​Not​Used</a></code></td>
    <td>This middleware is not used in this server configuration</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.MultipleObjectsReturned.html" class="internal-link" title="django.core.exceptions.MultipleObjectsReturned">​Multiple​Objects​Returned</a></code></td>
    <td>The query returned multiple objects when only one was expected.</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.ObjectDoesNotExist.html" class="internal-link" title="django.core.exceptions.ObjectDoesNotExist">​Object​Does​Not​Exist</a></code></td>
    <td>The requested object does not exist</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.PermissionDenied.html" class="internal-link" title="django.core.exceptions.PermissionDenied">​Permission​Denied</a></code></td>
    <td>The user did not have permission to do that</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.RequestAborted.html" class="internal-link" title="django.core.exceptions.RequestAborted">​Request​Aborted</a></code></td>
    <td>The request was closed before it was completed, or timed out.</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.RequestDataTooBig.html" class="internal-link" title="django.core.exceptions.RequestDataTooBig">​Request​Data​Too​Big</a></code></td>
    <td>The size of the request (excluding any file uploads) exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.SuspiciousFileOperation.html" class="internal-link" title="django.core.exceptions.SuspiciousFileOperation">​Suspicious​File​Operation</a></code></td>
    <td>A Suspicious filesystem operation was attempted</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.SuspiciousMultipartForm.html" class="internal-link" title="django.core.exceptions.SuspiciousMultipartForm">​Suspicious​Multipart​Form</a></code></td>
    <td>Suspect MIME request in multipart form data</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.SuspiciousOperation.html" class="internal-link" title="django.core.exceptions.SuspiciousOperation">​Suspicious​Operation</a></code></td>
    <td>The user did something suspicious</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.SynchronousOnlyOperation.html" class="internal-link" title="django.core.exceptions.SynchronousOnlyOperation">​Synchronous​Only​Operation</a></code></td>
    <td>The user tried to call a sync-only function from an async context.</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.TooManyFieldsSent.html" class="internal-link" title="django.core.exceptions.TooManyFieldsSent">​Too​Many​Fields​Sent</a></code></td>
    <td>The number of fields in a GET or POST request exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.ValidationError.html" class="internal-link" title="django.core.exceptions.ValidationError">​Validation​Error</a></code></td>
    <td>An error while validating data.</td>
  </tr><tr class="class">
    
    <td>Class</td>
    <td><code><a href="django.core.exceptions.ViewDoesNotExist.html" class="internal-link" title="django.core.exceptions.ViewDoesNotExist">​View​Does​Not​Exist</a></code></td>
    <td>The requested view does not exist</td>
  </tr><tr class="constant">
    
    <td>Constant</td>
    <td><code><a href="#NON_FIELD_ERRORS" class="internal-link" title="django.core.exceptions.NON_FIELD_ERRORS">NON​_FIELD​_ERRORS</a></code></td>
    <td><span class="undocumented">Undocumented</span></td>
  </tr>
</table>
        

          
      </div>

      <div id="childList">

        <div class="baseconstant">
  
  
  <a name="django.core.exceptions.NON_FIELD_ERRORS">
    
  </a>
  <a name="NON_FIELD_ERRORS">
    
  </a>
  <div class="functionHeader">
    
    <span class="py-defname">NON_FIELD_ERRORS</span>: <code><a href="https://docs.python.org/3/library/stdtypes.html#str" class="intersphinx-link">str</a></code> =
    <a class="sourceLink" href="https://github.com/pydocbrowser/pydocbrowser.github.io/tree/main/build/sources/django-4.0.2//django/core/exceptions.py#L104">
      
      (source)
    </a>
  </div>
  <div class="functionBody">
    
    
    <div><p class="undocumented">Undocumented</p></div>
    <table class="valueTable"><tr class="fieldStart"><td class="fieldName">Value</td></tr><tr><td><pre class="constant-value"><code><span class="rst-variable-quote">'</span><span class="rst-variable-string">__all__</span><span class="rst-variable-quote">'</span></code></pre></td></tr></table>
  </div>
</div>

      </div>
    </div>

    <footer class="navbar navbar-default">
  
  <div class="container">
    <a href="index.html">API Documentation</a> for django,
  generated by <a href="https://github.com/twisted/pydoctor/">pydoctor</a>
    22.2.1 at 2022-02-23 21:26:55.
  </div>
</footer>

    <script src="pydoctor.js" type="text/javascript"></script>

  </body>
</html>